package com.design;

import io.javalin.http.Context;
import io.javalin.http.Handler;
import org.jetbrains.annotations.NotNull;
import java.util.List;

public class BriefWebView implements Handler {

    private final BriefController controller;

    @javax.inject.Inject
    public BriefWebView(BriefController controller) {
        this.controller = controller;
    }

    @Override
    public void handle(@NotNull Context ctx) throws Exception {
        // Отримуємо список брифів
        List<Brief> briefs = controller.getAllBriefs();
        
        StringBuilder html = new StringBuilder();

        html.append("<!DOCTYPE html>");
        html.append("<html lang='uk'>");
        html.append("<head><meta charset='UTF-8'><title>Design Studio Briefs</title>");
        html.append("<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'>");
        html.append("</head><body>");
        html.append("<div class='container mt-5'>");
        
        html.append("<h1 class='mb-4'>Список Брифів (Design Projects)</h1>");
        
        html.append("<table class='table table-striped table-hover'>");
        html.append("<thead class='table-dark'><tr>");
        html.append("<th>ID</th>");
        html.append("<th>Назва проєкту (Title)</th>");
        html.append("<th>Опис (Description)</th>");
        html.append("</tr></thead><tbody>");
        
        for (Brief b : briefs) {
            html.append("<tr>");
            html.append("<td>").append(b.getId()).append("</td>");
            html.append("<td>").append(b.getTitle()).append("</td>");
            html.append("<td>").append(b.getDescription()).append("</td>");
            html.append("</tr>");
        }

        html.append("</tbody></table>");
        html.append("<footer class='mt-5 text-muted'>Generated by Javalin & Guice for Design Variant</footer>");
        html.append("</div></body></html>");

        ctx.html(html.toString());
    }
}