package com.design;

import io.javalin.http.Context;
import io.javalin.http.Handler;
import org.jetbrains.annotations.NotNull;
import java.util.List;

public class PayrollWebView implements Handler {

    private final PayrollController controller;

    // Інжектуємо контролер
    @javax.inject.Inject
    public PayrollWebView(PayrollController controller) {
        this.controller = controller;
    }

    @Override
    public void handle(@NotNull Context ctx) throws Exception {
        // Отримуємо дані з бази через контролер
        List<Paycheck> paychecks = controller.getAllPaychecks();
        
        StringBuilder html = new StringBuilder();

        // Початок HTML
        html.append("<!DOCTYPE html>");
        html.append("<html lang='uk'>");
        html.append("<head>");
        html.append("<meta charset='UTF-8'>");
        html.append("<title>Система нарахування зарплати</title>");
        // Підключаємо Bootstrap для гарного вигляду таблиці
        html.append("<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'>");
        html.append("</head>");
        
        html.append("<body>");
        html.append("<div class='container mt-5'>");
        html.append("<h1 class='mb-4'>Список виплат (Paychecks)</h1>");
        
        // Таблиця
        html.append("<table class='table table-striped table-hover'>");
        html.append("<thead class='table-dark'><tr>");
        html.append("<th>ID</th>");
        html.append("<th>Сума (Amount)</th>");
        html.append("<th>Дата (Pay Date)</th>");
        html.append("</tr></thead>");
        
        html.append("<tbody>");
        
        // Цикл по всіх чеках
        for (Paycheck p : paychecks) {
            html.append("<tr>");
            html.append("<td>").append(p.getId()).append("</td>");
            html.append("<td>").append(String.format("%.2f грн", p.getAmount())).append("</td>");
            html.append("<td>").append(p.getPayDate()).append("</td>");
            html.append("</tr>");
        }

        html.append("</tbody>");
        html.append("</table>");
        
        // Футер
        html.append("<footer class='mt-5 text-muted'>Generated by Javalin & Guice</footer>");
        html.append("</div>"); // кінець container
        html.append("</body></html>");

        // Віддаємо HTML браузеру
        ctx.html(html.toString());
    }
}